# .github/release.yml

changelog:
  exclude:
    labels:
      - duplicate
    authors:
      - Danaclocs
  categories:
    - title: Team Leader and Client Liaison
      labels:
        - Slothman1
    - title: Development Manager and Planning Manager
      labels:
        - dau501
    - title: Support Manager and Developer
      labels:
        - finnmcgearey
        - NickMcK14
    - title: Quality Manager and Developer
      labels:
        - vkach
        - Huy-GV
    - title: Dropped
      labels:
        - invalid
        - wontfix
    - title: Other Changes
      labels:
        - "*"
