# .github/release.yml

changelog:
  exclude:
    labels:
      - duplicate
    authors:
      - Danaclocs
  categories:
    - title: Test Plan
      labels:
        - test
    - title: Usability Evaluation Plan
      labels:
        - eval
    - title: Test Report
      labels:
        - test-report
    - title: Usability Assessment Report
      labels:
        - usability-report
    - title: Technical Documentations
      labels:
        - technical
    - title: Robotic Operating System and Collaborative Robot
      labels:
        - ROS2
    - title: Artificial Intelligence
      labels:
        - AI
    - title: Team Leader and Client Liaison
      labels:
        - Slothman1
    - title: Development Manager and Planning Manager
      labels:
        - dau501
    - title: Support Manager and Developer
      labels:
        - finnmcgearey
        - NickMcK14
    - title: Quality Manager and Developer
      labels:
        - vkach
        - Huy-GV
    - title: Dropped
      labels:
        - invalid
        - wontfix
    - title: Other Changes
      labels:
        - "*"
