blank_issues_enabled: true
contact_links:
  - name: Software Engineering Project B Discussions
    url: https://github.com/kanbanyte/sepb/discussions
    about: "Please make a Discussion, Issues can be created from Discussions."
