publisher_scaled_joint_trajectory_controller:
  ros__parameters:

    controller_name: "scaled_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [-1.154, -2.148, 2.035, -2.452, -1.949, -6.049]
    pos2:
      positions: [-0.0166, -1.905, 2.047, -1.721, -1.589, -3.322]
    pos3:
      positions: [-0.291, -1.466, 2.326, -2.440, -1.596, -3.412]
    pos4:
      positions: [-0.166, -1.905, 2.047, -1.721, -1.589, -3.323]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      shoulder_pan_joint: [-2,2]
      shoulder_lift_joint: [-3,-1]
      elbow_joint: [-0.1,3]
      wrist_1_joint: [-3,0]
      wrist_2_joint: [-3,0.1]
      wrist_3_joint: [-7,0.1]

publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [-1.154, -2.148, 2.035, -2.452, -1.949, -6.049]
    pos2:
      positions: [-0.0166, -1.905, 2.047, -1.721, -1.589, -3.322]
    pos3:
      positions: [-0.291, -1.466, 2.326, -2.440, -1.596, -3.412]
    pos4:
      positions: [-0.166, -1.905, 2.047, -1.721, -1.589, -3.323]


    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      shoulder_pan_joint: [-2,2]
      shoulder_lift_joint: [-3,-1]
      elbow_joint: [-0.1,3]
      wrist_1_joint: [-3,0]
      wrist_2_joint: [-3,0.1]
      wrist_3_joint: [-7,0.1]
