onrobot_rg6:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers
  joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_joint
    pid: {p: 1.0, i: 0.5, d: 1.0}

/gazebo_ros_control:   
  pid_gains:
    finger_joint:
      p: 1.0
      i: 0.5
      d: 1.0